using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float speed = 5f;
    public Vector3 movement;
    public Rigidbody rb;
    public int floorMaskG;
    public int floorMaskE;
    public int floorMaskN;
    public float camRayLength = 100f;

    private void Awake()
    {
        floorMaskG = LayerMask.GetMask("Floor");
        floorMaskE = LayerMask.GetMask("Enemy");
        floorMaskN = LayerMask.GetMask("FloorNoNav");
        rb = GetComponent<Rigidbody>();
    }

    private void FixedUpdate()
    {
        float h = Input.GetAxisRaw("Horizontal");
        float v = Input.GetAxisRaw("Vertical");

        Move(h, v);
        Turning();
    }

    private void Move(float h, float v)
    {
        movement.Set(h, 0f, v);
        movement = movement.normalized * speed * Time.deltaTime;
        rb.MovePosition(transform.position + movement);
    }

    private void Turning()
    {
        Ray camRay = Camera.main.ScreenPointToRay(Input.mousePosition);

        RaycastHit floorHit;

        if (Physics.Raycast(camRay, out floorHit, camRayLength, floorMaskG) 
            || Physics.Raycast(camRay, out floorHit, camRayLength, floorMaskE)
            || Physics.Raycast(camRay, out floorHit, camRayLength, floorMaskN))
        {
            Vector3 playerToMouse = floorHit.point - transform.position;
            playerToMouse.y = 0f;
            Quaternion newRotation = Quaternion.LookRotation(playerToMouse);
            rb.MoveRotation(newRotation);
        }
    }
}
